Title: Moses David Castro Portfolio
Logo: 
show_downloads: true
# theme: jekyll-theme-metadata
remote_theme: pages-themes/metadata@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
